___
# Capítulo 3 - Matemática e Estatística Básicas
## Seção 2 - Matrizes e NumPy
___

In [3]:
import numpy as np
from numpy.random import randn

In [4]:
np.set_printoptions(precision=2) #duas casas decimais

### Multiplicando matrizes e arrays

In [5]:
a = np.arange(3)
a

array([0, 1, 2])

In [6]:
aa = np.array([[2.,4.,6.], [1.,3.,5.], [10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [7]:
a * aa

array([[ 0.,  4., 12.],
       [ 0.,  3., 10.],
       [ 0., 20., 60.]])

### Multiplicando matrizes e Produto escalar

In [8]:
bb = np.arange(9).reshape((3,3))
bb

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
aa * bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

#### np.dot(primeira_matriz, segunda_matriz)

♔┈♔┈♔┈( O QUE ISSO FAZ ) ┈♔┈♔┈♔

Para executar a multiplicação de matrizes usamos o método do NumPy `np.dot()` passando para ele, as duas matrizes que queremos multiplicar.

In [10]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [11]:
b = a * 3
b

array([0, 3, 6])

In [12]:
np.dot(a, b)

15